### ISSUE TITLE
import RapidocCustomOptions 

### ISSUE THREAD

**Issue by olexiyb** [tsabolov/nestjs-rapidoc#1]
I have had to use
```
import type { RapidocCustomOptions } from '@b8n/nestjs-rapidoc/lib/interfaces/rapidoc-custom-options.interface';
```
When I expect

```
import type { RapidocCustomOptions } from '@b8n/nestjs-rapidoc'
```

**Comment by tsabolov** [comment]
The problem has been resolved in version 1.0.5 ([#e4f1a04](https://github.com/tsabolov/nestjs-rapidoc/commit/e4f1a04090f5934cf8433e5d1aab3cfc8910c6d6)). Please update your dependency to the latest version. Feel free to inform me if it resolves the issue for you.
