### ISSUE TITLE
Can addServer be automatically completed without configuration?

### ISSUE THREAD

**Issue by ausir0726** [tsabolov/nestjs-rapidoc#3]
This is a great work.

I have switched from swagger UI to Rapidoc, but unfortunately, it does not work correctly as per the official example. I have to add `.addServer('http://localhost:3000')` to make Rapidoc work.

On the other hand, Swagger UI works fine and during tryouts, it connects according to the endpoint specified.

Is there a better way to handle this to avoid hard coding the URL setting?

Thank you.

**Comment by ausir0726** [comment]
Another way is to use rapidocOptions.serverUrl: 'http://localhost:3000' to specify the API endpoint. However, I don't want to have hardcoded URLs in my configuration file. Is there a way to specify a request URL to use as the serverUrl instead?

**Comment by cheymos** [comment]
> Another way is to use rapidocOptions.serverUrl: 'http://localhost:3000' to specify the API endpoint. However, I don't want to have hardcoded URLs in my configuration file. Is there a way to specify a request URL to use as the serverUrl instead?

Use "/" instead. This works for me.

**Comment by ausir0726** [comment]
@cheymos 
Great, a simple and effective method.

@tsabolov 
Should rapidocOptions.serverUrl : '/' be added as a default value to ensure rapidoc works out of the box?
Currently, not specifying a server url will cause a failure.

**Comment by tsabolov** [comment]
Should be fixed in https://github.com/tsabolov/nestjs-rapidoc/releases/tag/v1.0.8
